<?php
/**
 * @file
 * Hook implementations for twitter_post module.
 */

/**
 * Implements hook_menu().
 */
function twitter_post_menu() {
  $items = array();

  $items['admin/settings/twitter/post'] = array(
    'title' => 'Post',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('twitter_post_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'twitter_post.pages.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 3,
  );

  return $items;
}

/**
 * Implements hook_perm().
 */
function twitter_post_perm() {
  return array('post to twitter');
}

/**
 * Implements hook_form_alter().
 */
function twitter_post_form_alter(&$form, $form_state, $form_id) {
  $max_field_length = 256; //initialized max length
  $max_length_twitter = 100;
  
  // If we haven't enabled Twitter posting on this node type, nothing to do here.
  $allowed_types = variable_get('twitter_post_types', array());
  if (isset($form['#node']) && $form['#node']->type . '_node_form' == $form_id) {
    $type = $form['#node']->type;
    $allowed_types = variable_get('twitter_post_types', array());
    if (empty($allowed_types[$type])) {
      return;
    }

    module_load_include('inc', 'twitter');
    $twitter_form = twitter_post_form();
    if (!$twitter_form) {
      return;
    }
    $form['twitter'] = array(
      '#type' => 'fieldset',
      '#group' => 'additional_settings',
      //'#title' => t('Post to Twitter.com'),
      '#title' => t(''),
      '#collapsible' => FALSE,
      '#collapsed' => FALSE,
      '#tree' => TRUE,
        
    );
    $form['twitter']['post'] = array(
      '#type' => 'checkbox',
      '#title' => t('Announce this post on Twitter'),
      '#default_value' => variable_get('twitter_post_default_value', 0),
      '#id' => 'twitter-toggle',
    );
    $form['twitter'] += $twitter_form;
    $form['twitter']['status']['#default_value'] = variable_get('twitter_post_default_format', 'New post: !title !url-alias');
   // $form['twitter']['status']['#description'] = t('The given text will be posted to twitter.com. You can use !url, !url-alias, !tinyurl, !title and !user as replacement text.');
   // $form['twitter']['status']['#maxlength'] = 150;
    $form['twitter']['status']['#description'] = t('Der hier eingegebene Text wird auf Twitter.com im Kanal @DemoScreen veröffentlicht, nachdem er zuvor durch den Hashtag #demografie sowie einen' 
          .'TinyURL-Link zu diesem Beitrag erweitert wurde. Daher stehen Ihnen für den eigenen Text nur '. $max_length_twitter.' Zeichen zur Verfügung. Fügen Sie in diesem Feld die Zeichenkette '
          .'\'!titel\' ein, so wird diese vor der Übertragung zu Twitter durch den Inhalt des Eingabefeldes \'Titelzeile\' ersetze. Wenn Sie dieses Eingabefeld leer lassen, '
          .'wird ausschließlich der Inhalt aus dem Feld \'Titelzeile\' als Nachricht für Twitter.com verwendet. <BR><BR> Noch <strong>' . $max_length_twitter . '</strong> weitere Zeichen können zu Twitter übertragen werden');
    $form['twitter']['status']['#maxlength'] = $max_field_length;
    $form['title']['#description'] = t('Enter title here');
    twitter_include_token_fields($form);
  }
}

/**
 * Implementation of hook_content_extra_fields().
 *
 * Let's the Twitter field be positioned within the edit node form.
 */
function twitter_post_content_extra_fields($type) {
  $allowed_types = variable_get('twitter_types', array('story' => 'story', 'blog' => 'blog'));

  if (empty($allowed_types[$type])) {
    return;
  }
  $extras['twitter'] = array(
    'label' => t('Twitter'),
    'description' => t('Form to send new content to twitter'),
    'weight' => 100,
  );
  return $extras;
}

/**
 * Implementation of hook_nodeapi().
 *
 * Intercepts newly published nodes and posts noticed to Twitter.
 */
function twitter_post_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  $max_length_twitter = 100;
  switch ($op) {
    case 'insert':
    case 'update':
      if (!empty($node->status) && !empty($node->twitter) && !empty($node->twitter['post'])) {
        //The status needs to be truncated after replacement of !title. Inserting default extension of the status
        $node->twitter['status'] = str_ireplace('!titel', $node->title, $node->twitter['status']);
        $node->twitter['status'] = substr($node->twitter['status'], 0, $max_length_twitter)." !tinyurl #demografie";
        
        module_load_include('inc', 'twitter');

        $twitter_account = twitter_account_load($node->twitter['account']);
        $replacements = array(
          '!titel' => $node->title,
          '!url' => url('node/' . $node->nid, array('absolute' => TRUE, 'alias' => TRUE)),
          '!url-alias' => url('node/' . $node->nid, array('absolute' => TRUE)),
          '!user' => $node->name,
        );

        // Only generate the shortened URL if it's going to be used. No sense
        // burning through TinyURLs without a good reason.
        if (strstr($node->twitter['status'], '!tinyurl') !== FALSE) {
          $replacements['!tinyurl'] = twitter_shorten_url(url('node/' . $node->nid, array('absolute' => TRUE)));
        }

        $status = strtr($node->twitter['status'], $replacements);

        // If token module is available, process status to do the token replacement
        if (module_exists('token')) {
          $status = token_replace($status, 'node', $node);
        }

        if (twitter_set_status($twitter_account, $status)) {
          drupal_set_message(t('Successfully posted to Twitter'));
        }
        else {
          drupal_set_message(t('Could not post to Twitter. Please check the site reports.'));
        }
      }
      break;
  }
}

/**
 * Generate a twitter posting form for the given user.
 *
 * @param $account
 *   A Drupal user object.
 */
function twitter_post_form($account = NULL) {
  if (empty($account)) {
    global $user;
    $account = $user;
  }
  if (!user_access('post to twitter', $account)) {
    return;
  }

  drupal_add_js(drupal_get_path('module', 'twitter_post') . '/twitter_post.js');
  $options = array();
  $twitter_accounts = twitter_load_authenticated_accounts();
  foreach ($twitter_accounts as $twitter_account) {
    $options[$twitter_account->id] = $twitter_account->screen_name;
  }

  if (count($options)) {
    $form = array();
    $form['status'] = array(
      '#type' => 'textfield',
      '#id' => 'twitter-textfield',
    );

    if (count($options) > 1) {
      $form['account'] = array(
        '#type' => 'select',
        '#title' => t('Account'),
        '#options' => $options,
        '#id' => 'twitter-account',
      );
    }
    else {
      $options_keys = array_keys($options);
      $form['account'] = array(
        '#type' => 'value',
        '#value' => array_pop($options_keys),
      );
    }
    return $form;
  }
}

/**
 * Add token help fields to the passed form.
 *
 * @param $form
 *   A Drupal Forms API form.
 */
function twitter_include_token_fields(&$form){
  if (module_exists('token')) {
    $form['twitter']['token_help'] = array(
      '#title' => t('Replacement patterns'),
      '#type' => 'fieldset',
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
      '#description' => t('Prefer raw-text replacements for text to avoid problems with HTML entities!'),
      '#access' => false,
    );

    $form['twitter']['token_help']['help'] = array(
      '#value' => theme('token_help', 'node'),
    );
  }
}
